# Generated by Django 5.1.4 on 2024-12-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_projectrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='status',
            field=models.CharField(choices=[('در حال پردازش', 'در حال پردازش'), ('پذیرفته شده توسط تیم پی.آر', 'پذیرفته شده توسط تیم پی.آر'), ('پذیرفته شده توسط شما و پی.آر', 'پذیرفته شده توسط شما و پی.آر'), ('در حال انجام پروژه', 'در حال انجام پروژه'), ('تکمیل شده', 'تکمیل شده'), ('لغو شده', 'لغو شده')], default='pending', max_length=40),
        ),
    ]
