# Generated by Django 5.1.4 on 2024-12-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_projectrequest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'درحال پردازش'), ('Final approval', 'Final approval'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
