# Generated by Django 5.1.4 on 2024-12-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_projectrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='status',
            field=models.CharField(choices=[('در حال پردازش', 'Pending Approval'), ('پذیرفته شده توسط تیم پی.آر', 'Approval'), ('پذیرفته شده توسط شما و پی.آر', 'Final approval'), ('در حال انجام پروژه', 'In Progress'), ('تکمیل شده', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=40),
        ),
    ]
